BEGIN;

DROP TABLE IF EXISTS users CASCADE;

CREATE TABLE users (
  id SERIAL PRIMARY KEY UNIQUE,
  username VARCHAR(255) UNIQUE,
  email VARCHAR(255) UNIQUE,
  password VARCHAR(1000),
  bio VARCHAR(500),
  YOB INTEGER,
  photo VARCHAR(255),
  groups VARCHAR(255),
  created TIMESTAMP,
  last_login TIMESTAMP,
  predictions VARCHAR(500),
  points INTEGER,
  paid BOOLEAN
);

DROP TABLE IF EXISTS comments CASCADE;

CREATE TABLE comments (
  id SERIAL PRIMARY KEY UNIQUE,
  user_Id  INTEGER NOT NULL REFERENCES users(id),
  comment VARCHAR(500) NOT NULL ,
  created TIMESTAMP NOT NULL
);

DROP TABLE IF EXISTS teams CASCADE;

CREATE TABLE teams (
  id SERIAL PRIMARY KEY UNIQUE,
  name VARCHAR (255) NOT NULL,
  fifaCode VARCHAR (500) NOT NULL ,
  flag VARCHAR (255) NOT NULL
);

DROP TABLE IF EXISTS matches CASCADE;

CREATE TABLE matches (
  id SERIAL PRIMARY KEY UNIQUE,
  team1 INTEGER NOT NULL REFERENCES teams(id),
  team2 INTEGER NOT NULL REFERENCES teams(id),
  kickoff TIMESTAMP,
  final_score VARCHAR (255)
);

DROP TABLE IF EXISTS changes CASCADE;

CREATE TABLE changes (
  id SERIAL PRIMARY KEY UNIQUE,
  user_id INTEGER NOT NULL  REFERENCES users(id),
  match_id INTEGER NOT NULL  REFERENCES matches(id),
  time_stamp TIMESTAMP NOT NULL ,
  type VARCHAR (255) NOT NULL
);

DROP TABLE IF EXISTS groups CASCADE;

CREATE TABLE groups (
  id SERIAL PRIMARY KEY UNIQUE,
  name VARCHAR(255) NOT NULL,
  colour_code VARCHAR(255)
);

COMMIT;
